const seedDeliveries = [
  { id: 'RX-1048', customer: 'Amina Wanjiku', phone: '0712 456 890', address: 'Kileleshwa, Nairobi', item: 'Samsung Galaxy A15', status: 'Open', rider: null, created: '8 min ago', code: null },
  { id: 'RX-1047', customer: 'Brian Otieno', phone: '0798 123 455', address: 'Lavington, Nairobi', item: 'Makita power drill', status: 'Assigned', rider: 'David K.', created: '24 min ago', code: 'K7M4Q' },
  { id: 'RX-1046', customer: 'Mary Njeri', phone: '0701 887 234', address: 'Parklands, Nairobi', item: 'iPhone 13 screen protector', status: 'Picked Up', rider: 'Samuel O.', created: '1 hr ago', code: 'P2X8L' },
  { id: 'RX-1045', customer: 'Kevin Mwangi', phone: '0722 334 901', address: 'Kilimani, Nairobi', item: 'JBL Flip 6 speaker', status: 'Delivered', rider: 'David K.', created: '2 hrs ago', code: 'H9Q3R' },
  { id: 'RX-1044', customer: 'Faith Achieng', phone: '0744 610 778', address: 'South B, Nairobi', item: 'USB-C charging hub', status: 'Delivered', rider: 'Samuel O.', created: '3 hrs ago', code: 'D6T1N' }
];
let deliveries = JSON.parse(localStorage.getItem('reflex-deliveries')) || seedDeliveries;
let currentRole = 'dispatcher';
const riders = [{ name: 'David K.', initials: 'DK', deliveries: 2, color: '#f4c95d' }, { name: 'Samuel O.', initials: 'SO', deliveries: 2, color: '#dcebf1' }, { name: 'Lucy W.', initials: 'LW', deliveries: 0, color: '#e8d7e4' }];
const appView = document.getElementById('app-view');
const toast = document.getElementById('toast');
function save(){ localStorage.setItem('reflex-deliveries', JSON.stringify(deliveries)); }
function showToast(message){ toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
function statusClass(status){ return status.toLowerCase().replace(' ', '-'); }
function statusPill(status){ return `<span class="status ${statusClass(status)}">${status}</span>`; }
function header(title, subtitle, action=''){ return `<div class="page-heading"><div><p class="eyebrow">${currentRole === 'dispatcher' ? 'Tuesday, 14 May 2024' : 'Your delivery desk'}</p><h1>${title}</h1><p class="subheading">${subtitle}</p></div>${action}</div>`; }
function metrics(){ const open = deliveries.filter(d=>d.status==='Open').length; const active = deliveries.filter(d=>['Assigned','Picked Up'].includes(d.status)).length; const done = deliveries.filter(d=>d.status==='Delivered').length; return `<div class="metrics"><div class="metric-card"><div class="metric-top">Open requests <span class="metric-icon">+</span></div><div class="metric-value">${open}<span class="metric-delta">today</span></div></div><div class="metric-card"><div class="metric-top">In progress <span class="metric-icon">↗</span></div><div class="metric-value">${active}<span class="metric-delta">active</span></div></div><div class="metric-card"><div class="metric-top">Delivered today <span class="metric-icon">✓</span></div><div class="metric-value">${done}<span class="metric-delta">+12%</span></div></div><div class="metric-card"><div class="metric-top">Avg. delivery <span class="metric-icon">◷</span></div><div class="metric-value">42<span class="metric-delta">min</span></div></div></div>`; }
function deliveryRows(items){ if(!items.length) return '<div class="empty-state">No deliveries match this view.</div>'; return `<table class="delivery-table"><thead><tr><th>Delivery</th><th>Customer</th><th>Status</th><th>Rider</th><th></th></tr></thead><tbody>${items.map(d=>`<tr><td><span class="delivery-id">${d.id}</span><span class="address">${d.created}</span></td><td><span class="customer">${d.customer}</span><span class="address">${d.address}</span></td><td>${statusPill(d.status)}</td><td><span class="rider-name">${d.rider || 'Unassigned'}</span></td><td>${currentRole==='dispatcher'&&d.status==='Open'?`<button class="text-button" data-assign="${d.id}">Assign</button>`:`<button class="text-button" data-track="${d.id}">View</button>`}</td></tr>`).join('')}</tbody></table><div class="mobile-table-card">${items.map(d=>`<div class="delivery-row"><div class="delivery-row-top"><span class="delivery-id">${d.id}</span>${statusPill(d.status)}</div><span class="customer">${d.customer}</span><span class="address">${d.address}</span><div class="delivery-row-bottom"><span>${d.rider || 'Unassigned'} · ${d.created}</span>${currentRole==='dispatcher'&&d.status==='Open'?`<button class="text-button" data-assign="${d.id}">Assign</button>`:`<button class="text-button" data-track="${d.id}">View</button>`}</div></div>`).join('')}</div>`; }
function recentActivity(){ return `<div class="panel"><div class="panel-header"><div><h2 class="panel-title">Recent activity</h2><p class="panel-subtitle">A quick look at what changed</p></div><button class="text-button" data-view="activity">See all</button></div><div class="activity-list"><div class="activity-item"><span class="activity-dot">↗</span><div><p><b>David K.</b> was assigned to <b>RX-1047</b></p><time>24 minutes ago</time></div></div><div class="activity-item"><span class="activity-dot">✓</span><div><p><b>RX-1045</b> marked as delivered</p><time>2 hours ago</time></div></div><div class="activity-item"><span class="activity-dot">+</span><div><p>New request <b>RX-1048</b> was created</p><time>8 minutes ago</time></div></div></div></div>`; }
function renderOverview(){ const open = deliveries.filter(d=>d.status==='Open'); appView.innerHTML = header('Good morning, Jane', 'Here is what is happening with your deliveries today.', '<button class="primary-button" id="new-request">+ New delivery</button>') + metrics() + `<div class="dashboard-grid"><div class="panel"><div class="panel-header"><div><h2 class="panel-title">Open requests</h2><p class="panel-subtitle">Assign a rider to keep things moving</p></div><button class="text-button" data-view="deliveries">View all</button></div>${deliveryRows(open)}</div>${recentActivity()}</div>`; }
function renderDeliveries(){ appView.innerHTML = header('Deliveries', 'Track every request from the shop to the customer.', '<button class="primary-button" id="new-request">+ New delivery</button>') + `<div class="list-toolbar"><input class="search-box" id="search" placeholder="Search by ID, customer or address" /><select class="filter-select" id="status-filter"><option value="all">All statuses</option><option>Open</option><option>Assigned</option><option>Picked Up</option><option>Delivered</option></select></div><div class="panel" id="delivery-panel">${deliveryRows(deliveries)}</div>`; document.getElementById('search').addEventListener('input', filterDeliveries); document.getElementById('status-filter').addEventListener('change', filterDeliveries); }
function filterDeliveries(){ const term=document.getElementById('search').value.toLowerCase(); const filter=document.getElementById('status-filter').value; const items=deliveries.filter(d=>(filter==='all'||d.status===filter)&&[d.id,d.customer,d.address].join(' ').toLowerCase().includes(term)); document.getElementById('delivery-panel').innerHTML=deliveryRows(items); bindDynamic(); }
function renderRiders(){ appView.innerHTML=header('Riders', 'Your delivery team and their current workload.') + `<div class="rider-cards">${riders.map(r=>`<div class="rider-card"><div class="rider-card-head"><span class="rider-avatar" style="background:${r.color}">${r.initials}</span><div><h3>${r.name}</h3><small>Westlands area</small></div></div><p class="availability">● Available now</p><div class="rider-stat"><span>Active deliveries</span><strong>${r.deliveries}</strong></div></div>`).join('')}</div>`; }
function renderActivity(){ appView.innerHTML=header('Activity', 'A complete record of changes across your workspace.') + `<div class="panel"><div class="activity-list"><div class="activity-item"><span class="activity-dot">↗</span><div><p><b>Jane Mwangi</b> assigned <b>RX-1047</b> to David K.</p><time>Today, 10:42 AM</time></div></div><div class="activity-item"><span class="activity-dot">✓</span><div><p><b>RX-1045</b> was marked delivered by David K.</p><time>Today, 9:18 AM</time></div></div><div class="activity-item"><span class="activity-dot">✓</span><div><p><b>RX-1046</b> was picked up by Samuel O.</p><time>Today, 8:56 AM</time></div></div><div class="activity-item"><span class="activity-dot">+</span><div><p><b>Amina Wanjiku</b> created <b>RX-1048</b></p><time>Today, 8:49 AM</time></div></div></div></div>`; }
function renderRetailer(){ const mine=deliveries.slice(0,4); appView.innerHTML=header('Track a delivery', 'Stay in the loop without calling the shop.') + `<div class="panel" style="max-width:840px"><div class="panel-header"><div><h2 class="panel-title">Your recent deliveries</h2><p class="panel-subtitle">Status refreshes automatically every few seconds</p></div><button class="text-button" id="new-request">+ New request</button></div>${deliveryRows(mine)}</div>`; }
function renderRider(){ const assigned=deliveries.filter(d=>d.rider==='David K.' && d.status!=='Delivered'); appView.innerHTML=header('Your route today', `${assigned.length} deliveries are waiting for you.`) + `<div class="panel"><div class="panel-header"><div><h2 class="panel-title">Assigned to you</h2><p class="panel-subtitle">Update each stop as you move</p></div></div>${assigned.length ? deliveryRows(assigned).replace(/<button class="text-button" data-track="(.*?)">View<\/button>/g, '<button class="text-button" data-update="$1">Update</button>') : '<div class="empty-state">You are all caught up.</div>'}</div>`; }
function render(){ const activeView=document.querySelector('.nav-item.active')?.dataset.view || 'overview'; if(currentRole==='retailer') renderRetailer(); else if(currentRole==='rider') renderRider(); else if(activeView==='deliveries') renderDeliveries(); else if(activeView==='riders') renderRiders(); else if(activeView==='activity') renderActivity(); else renderOverview(); bindDynamic(); document.getElementById('delivery-count').textContent=deliveries.filter(d=>d.status==='Open').length; }
function openNewRequest(){ document.getElementById('modal-content').innerHTML=`<h2 id="modal-title">New delivery request</h2><p>Give your rider everything they need for a smooth handoff.</p><form class="form-grid" id="request-form"><div class="form-field"><label>Customer name</label><input required name="customer" placeholder="e.g. Amina Wanjiku" /></div><div class="form-field"><label>Phone number</label><input required name="phone" placeholder="07XX XXX XXX" /></div><div class="form-field"><label>Delivery address</label><input required name="address" placeholder="Area, street or landmark" /></div><div class="form-field"><label>Item description</label><input required name="item" placeholder="What is being delivered?" /></div><div class="form-actions"><button type="button" class="secondary-button" id="cancel-modal">Cancel</button><button class="primary-button">Create request</button></div></form>`; showModal(); document.getElementById('request-form').onsubmit=e=>{e.preventDefault(); const data=Object.fromEntries(new FormData(e.target)); deliveries.unshift({ ...data,id:'RX-'+(1049+deliveries.length),status:'Open',rider:null,created:'just now',code:null }); save(); closeModal(); render(); showToast('Delivery request created');}; document.getElementById('cancel-modal').onclick=closeModal; }
function openAssign(id){ const d=deliveries.find(x=>x.id===id); document.getElementById('modal-content').innerHTML=`<h2 id="modal-title">Assign ${id}</h2><p>Choose an available rider for ${d.customer}.</p><form class="form-grid" id="assign-form"><div class="form-field"><label>Rider</label><select name="rider" required><option value="">Select a rider</option>${riders.map(r=>`<option>${r.name}</option>`).join('')}</select></div><div class="form-actions"><button type="button" class="secondary-button" id="cancel-modal">Cancel</button><button class="primary-button">Assign delivery</button></div></form>`; showModal(); document.getElementById('assign-form').onsubmit=e=>{e.preventDefault(); d.rider=new FormData(e.target).get('rider'); d.status='Assigned'; d.code=Math.random().toString(36).slice(2,7).toUpperCase(); save(); closeModal(); render(); showToast(`${d.id} assigned successfully`);}; document.getElementById('cancel-modal').onclick=closeModal; }
function openUpdate(id){ const d=deliveries.find(x=>x.id===id); document.getElementById('modal-content').innerHTML=`<h2 id="modal-title">Update ${id}</h2><p>${d.customer} · ${d.address}</p><div class="form-actions" style="justify-content:stretch"><button class="secondary-button" style="flex:1" id="pickup">Mark picked up</button><button class="primary-button" style="flex:1" id="deliver">Confirm delivery</button></div><div class="form-field" style="margin-top:18px"><label>Confirmation code</label><input id="code-input" placeholder="Enter 5-character code" maxlength="5" /></div>`; showModal(); document.getElementById('pickup').onclick=()=>{d.status='Picked Up';save();closeModal();render();showToast('Delivery marked as picked up')}; document.getElementById('deliver').onclick=()=>{if(document.getElementById('code-input').value.toUpperCase()!==d.code){showToast('That confirmation code does not match');return}d.status='Delivered';save();closeModal();render();showToast('Delivery confirmed')}; }
function openTrack(id){ const d=deliveries.find(x=>x.id===id); const steps=['Open','Assigned','Picked Up','Delivered']; const current=steps.indexOf(d.status); document.getElementById('modal-content').innerHTML=`<h2 id="modal-title">${d.id}</h2><p>${d.customer} · ${d.item}</p><div class="track-head"><span class="track-id">${d.address}</span>${statusPill(d.status)}</div><div class="timeline">${steps.map((s,i)=>`<div class="timeline-step ${i<current?'complete':''} ${i===current?'current':''}"><span class="timeline-marker"></span><div><b>${s}</b><small>${i<current?'Completed':i===current?'Current status':'Up next'}</small></div></div>`).join('')}</div>${d.code?`<div class="code-box"><small>Confirmation code</small><br><strong>${d.code}</strong></div>`:''}`; showModal(); }
function showModal(){document.getElementById('modal-backdrop').hidden=false} function closeModal(){document.getElementById('modal-backdrop').hidden=true}
function bindDynamic(){ document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));const nav=document.querySelector(`.nav-item[data-view="${b.dataset.view}"]`);if(nav)nav.classList.add('active');render()}); document.querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>openTrack(b.dataset.track)); document.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>openAssign(b.dataset.assign)); document.querySelectorAll('[data-update]').forEach(b=>b.onclick=()=>openUpdate(b.dataset.update)); document.querySelectorAll('.delivery-row').forEach(row=>{const id=row.querySelector('.delivery-id')?.textContent; if(currentRole==='dispatcher'&&id&&deliveries.find(d=>d.id===id)?.status==='Open') row.onclick=e=>{if(!e.target.closest('button'))openAssign(id)} }); const newButton=document.getElementById('new-request');if(newButton)newButton.onclick=openNewRequest; }
document.querySelectorAll('.role-button').forEach(button=>button.onclick=()=>{currentRole=button.dataset.role;document.querySelectorAll('.role-button').forEach(b=>b.classList.toggle('active',b===button));render()}); document.getElementById('modal-close').onclick=closeModal; document.getElementById('modal-backdrop').onclick=e=>{if(e.target.id==='modal-backdrop')closeModal()};
render(); setInterval(()=>{document.querySelector('.sync-note small')?.replaceChildren(document.createTextNode('Updated just now'));},5000);
